language: java
install: true
sudo: false
os: linux
dist: trusty
services:
- docker
jdk:
- openjdk11
- openjdk12
script:
- "./gradlew build test integrationTest jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jobs:
  include:
  - stage: SpringBoot App - Docker Push
    jdk: openjdk11
    script:
    - "./gradlew clean build -x test --no-daemon"
    - application/springboot/docker-build.sh $TRAVIS_TAG
    - application/springboot/docker-push.sh $TRAVIS_TAG
    if: tag IS present
  - stage: Github Release
    jdk: openjdk11
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: HhTwRNJGFjBTz7pABDsmyYOwIl1OJm/hFUgTwe8FYDF+OyFRoh0nUkDmxHhmDLmZlpGqUBfWXDvrpgPXnDDAp6A0pv7yKq7yOdN9u2fBzeE0lUDbwT+EbgSAOBm+zJoT25syrBfaILfRg4LHceR7ZGHVzvJKg86d3xIY+O0qGijMIPqWdM7wavXsAYQBJBCQ8aZhEk/B/+7OY7U5FvkWD/1KJC1LjXN6qqM5VUKj8JuwcOwCm91caThd8HSitm5pHdZL1xmGa05C448b53odiKz5LneYv7jbxrz5p7P9IH+8V6aVZ+NSWBvUPOXnqy9ne3LY4dQbNnv+OZNvAgjau2zW/Th49IIv1IuMkAqzw/DjzRXaGjjAsESIlGjr+ymIDwvyvMYaLNnX7mdy/PsGLC7gZv1ByMIifgsgOBLy0Dri73GSTJ94qvqMBo+m/mLsQU1bhDFm9dpgKbxqdXb1Jc1yhYOGABTDtMjc1owEc5vW9XW4qynKzCYXoUl1cRjiAvyi3NEm+Hb/bP+0Y5s55Imw114fsJ/7ZMmuOvrpBIw7Md2htuMSTwn2iRjzEslUmW/6oimmHpZd4wCC+Lxy0hznQT6lhg4U5qyeee4C+SyAJKa8w7kKWOG7kuZqoE3hKpah/L2C6n9ON63unsdJ7yS7NWDJanbIC5BPUrFSQ+U=
      skip_cleanup: true
      on:
        tags: true
env:
  global:
  - DOCKER_REGISTRY=newpetstore-docker-docker.bintray.io
  - secure: oCwT2cdnFR+KjtZ9A7l/vT/1qgYC4bgtofQx5LDrza6BDry//Hs49kd+pzO5PcqzBG1HMT9z5pcRGuF7xzniHTR201XLT3ACOg+2fUMsWVwpETqhXM7SqaU85KhKQiJBGxtycQlDuGv+qnkt9dQ69jQOE3PrtIFLyPA9qPRnk1LQLcyqOBS+MTTO0jzUoYAcynGDeYOYPF8x0xxGOOssR1ueXEvBFgsqoRfjR1GkyNgJzScxpv2dr+4NsH37Y2XBcSJnaDFVd//tO5OCTWnYGSkgRTR8wJU1lXedeXXi3yngFj5A+HrdW0ND6l3MQA9grYIztSjzyfaQRC7mAKYZnbz+eHagfpbr/2eGW5NTGeErRUB8hZ0IKhqbwHuwhO3YIKPhgwLP2NB8EbefbXqojcpi/I0nxWC7li6qJBoZ3eMW9W5ClVHyMKIp2BzBwny9aQYVRlgrCXmynRl5fvktGIWlqDpfwMRafYsDLAEjoXdCMrEkIEo0415yKuWFqpvSU+d+Mw2r3IV9rFMTk3KfXlWdY1m/GCTUjnhYmCbqoaTkT8dmRB0By2YWosuGq9U3VX+FIisDXCp83nt1OsIa8m6p8JAS0AqbTwgsfQltbo7Tw5TYyQ3aPSl49GCCkgSHsw5vEhl1fpbkbRNDcEwfGcegM10UpIVeCJeuu1Vz1OU=
  - secure: dxs+UO1qTBpA4x/d8088vvH9T3YM4azQIi/RS1fJphYCT4SOzqfvT72c03cXXx50hcUGd31LYRBgb7sYcpVT2ETqQ044sHkBA92dLNLslAbZyyFmdr3X3hC2Mmt1bA+H/hCUKXWV4jXVDwcLw4btEnEugXUsGiK3A8TRtQl3iTB2V81YjVqfzfxUC6ZjCoJlbAJwAQhBzIWK8vWkH6X9d6fp5cJS45/wXar18yUe7QFsFGegx9b5kpzdHZ1S4ftwjftL8K+8Z3ag/82/VrEMV2AE2C7q5baD8ySeTCnKh290bj9dxJGW2DuCs3IjlRk83w1uOVUMCVwS8X3cIHpZLT2Uuk5btUO2ZT70AzQR33N74AcXxshEvUIn7B9fT9p1XcbrGpMqNu7PzpSszZBqUu5vP9HJ9WZ96YZb7GwIevbqO2vd7sNo29IuLZYTIDWD8nLN3YMrSO0Ls/s6pYsnazPUGbjIejmMYgIbo7pzR8AYyk/WGLVM83QEltBnrSRswPgUpiNO57OAzBsbFafvWWKSeVcgtYo7PKMd+A1gnBkRbahOtb1SNvuL2zelV4gNgUZYw6mhTwzQD1QS7klsBx6IjxxPiHUdp6YPxwhYTeoM1Nhmoae/3xrJs2mq5Ce0qmQVb58wbf62H2gmjdToLkxqcb7gZfobgEmr4yNSBMQ=
  - secure: o0x6X5er0Jl6kQ/PLxp6Yml0wCVjGm+AlIIUaE3PGB2cxP4LXTDQruJypZeXsJQCeTBCz/567CiZXMyt6gzMXlO/yVScMqUqyy+F7eNB7EeG3YLqIq4gYTQFAO2+mNPJH+4dfWXVynh/raJHbfOgDk1DwaAQO0iBVZp0ds4W9XZ0jyH7JSrfN/bVY3A9YXG9HEyopQCaeqqNW+JBkUNfxzhIhQCf09ukgndH/83VBr8zlkcQsuj/xVE/mhZF5huREfKsw54AQA5kElVFsosagbHqlRzZtNg0RsLItzl13VErzL1+FSWEk5l7l1y127aSPETbSXHkSIQqB3kqU/FjIfTKVcZb/KRew91eVp1iJC/6xDD3rwugGypAMIkxZ6XOkSk2uKSFJwhju+1PANgdMhG0/wJCrzqzkQJhQBI0v30hy9ENO0o3P9/c9FEO9VZZABb8Wtu9qL5oTZFxF7j1Zy5779SAlcnmK+M+zNN7/3gJ721fmSX+7ZXy3phVIIV6LT7pweIT5nqX0VDN3ksSBINSlLLB8OsBK7dBxJZrWRk/oaAF1rKeSkTn2od6bQmKZmpIXx96KJbgS+DYdAQ1jMUDUqZjPxYUlKTuvzvCYIGe8LfYdKdOPsO2k7/g5Kzo84myi/kuhMx3MH+behMeRZPWdAimgfn9piWLBN3E/rY=
