/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package petstore.category.domain;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

}
